### ISSUE TITLE
Is this repository being maintained?

### ISSUE THREAD

**Issue by famagusta** [locationlabs/mockredis#144]
Current master branch is way behind the original redis py library changes.
Pull requests are approved but not merged.
Is anyone maintaining this?

**Comment by tadeoiiit** [comment]
Should we fork it and make a fork the new version?

**Comment by tadeoiiit** [comment]
@andreaia @ber4444 @davidmnoriega @jbir789 @joshal @richfromm @ryan-west @TageNielsen
Do you plan to maintain this library? Would you consider giving it to someone else?
