### ISSUE TITLE
Multiple instances of mock_redis_client use separate data sources

### ISSUE THREAD

**Issue by tsitra** [locationlabs/mockredis#66]
The sample from http://seeknuance.com/2012/02/18/replacing-redis-with-a-python-mock/ shows a redis client that will always point to the same data source, where this mock will always point to a new data source.

Pushing data into a mocked up redis from within a test is important to testing using redis as a queue system.

**Comment by jessemyers** [comment]
Closing. It's reasonable to refile as "support connection pooling"
