### ISSUE TITLE
setup_requires nose in setup.py

### ISSUE THREAD

**Issue by meghnasapre** [locationlabs/mockredis#67]
We host our python dependencies in an internal repository, and this section in the setup.py:
 setup_requires=[
          'nose'
      ]
forces it to look at the pypi website, ignoring the --index-url provided. 
Is it possible to just add it to the requires.txt and exclude it from setup.py?

Thank you for a superb library, it works beautifully.

**Comment by jessemyers** [comment]
No update here in a while, assuming the workaround is sufficient.
